FRAME_QUEUE_SIZE = 10

DET_QUEUE_SIZE = 10

STAFF_SIMILARITY_THRESHOLD = 0.5

FACE_DETECTION_THRESHOLD = 0.55

MIN_FACE_WIDTH = 25

MIN_FACE_HEIGHT = 25

TRACKER_MAX_DISAPPEARED = 30

TRACKER_MAX_DISTANCE = 150

TRACKER_TYPE = "centroid" # Options: "centroid" or "bytetrack"

CAMERA_INDEX = 0

FRAME_WIDTH = 640

FRAME_HEIGHT = 480

MODEL_NAME = "buffalo_l"
DET_THRES = 0.4

URL="PRIVATE_URL"